# Made by Skyler Blue Spillers - Innovative Information Technology Resolutions LLC
version: '3.8'
services:
  shadowchat:
    build: .
    ports:
      - "4444:4444"
    deploy:
      replicas: 3
  p2p:
    build: .
    command: python p2p/node_p2p.py
    ports:
      - "4445:4445"