# Made by Skyler Blue Spillers - Innovative Information Technology Resolutions LLC
[supervisord]
nodaemon=true

[program:shadowchat]
command=uvicorn node:app --host 0.0.0.0 --port 4444
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/shadowchat.log
stderr_logfile=/var/log/shadowchat.err.log