# Made by Skyler Blue Spillers - Innovative Information Technology Resolutions LLC
apiVersion: v1
kind: Secret
metadata:
  name: shadowchat-secrets
type: Opaque
data:
  INFURA_KEY: BASE64_ENCODED_KEY
  PRIVATE_KEY: BASE64_ENCODED_KEY